dist: xenial

language: python

addons:
  postgresql: 10
  apt:
    packages:
    - postgresql-10-postgis-2.3
    - libgdal-dev
    - gdal-bin

cache:
  - pip

python:
 - "3.6"
 - "3.7-dev"

install:
 - pip install pipenv
 - pipenv install --dev

before_script:
  - psql -U postgres -c "create extension postgis"

script:
 - make test
